# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-30 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(blank=True, upload_to='static/%Y/%m/%d')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
